@if( app()->getLocale() == 'es' )
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
  <loc>https://publicidad-mercadolibre.com/</loc>
  <changefreq>monthly</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/main-slider</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/billboard</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/top-search-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/search-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/brandformance</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/product-ads</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/display-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/super-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/half-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/sponsored-deals</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/landings-customizadas</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/patrocinio-eventos</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/soluciones/servicios-relacionados</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/audiencias</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/insights</loc>
  <changefreq>monthly</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/casos-de-exito</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/por-que-nosotros</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/contacto</loc>
  <changefreq>monthly</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/casos-de-exito/Citroen-buscaron-audiencia-encontraron-compradores</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/insights/covid-2</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/insights/trends</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/insights/covid</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/insights/hot-sale</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/insights/hot-sale-argentina</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/pdf/mercado-libre-mediakit-ES.pdf</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/casos-de-exito/samsung-un-lanzamiento-a-medida-del-usuario</loc>
  <changefreq>monthly</changefreq>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/casos-de-exito/Huawei-un-evento-puso-a-su-marca-en-boca-de-todos</loc>
  <changefreq>monthly</changefreq>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/casos-de-exito/ford-revolucionaron-su-negocio-vendiendo-online</loc>
  <changefreq>monthly</changefreq>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/covid-2-es.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/mobile-es.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/desktop-es.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/mobile-en.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/desktop-en.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/covid-es.pdf</loc>
<url>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/hotsale-es.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidad-mercadolibre.com/assets/reports/hotsale-2-es.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
</urlset>
@endif

@if( app()->getLocale() == 'pt' )
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
  <loc>https://publicidade-mercadolivre.com/</loc>
  <changefreq>monthly</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/main-slider</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/billboard</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/top-search-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/search-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/brandformance</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/product-ads</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/arroba</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/fullscreen-ads</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/super-banner</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/half-banner</loc>
 <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/sponsored-deals</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/landings-customizadas</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/patrocinio-eventos</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/solucoes/Servi%C3%A7os-relacionados</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/audiencias</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/insights</loc>
  <changefreq>monthly</changefreq>
  <priority>1.00</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/casos-de-sucesso</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/porque-nos</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/contato</loc>
  <changefreq>monthly</changefreq>
  <priority>1.00</priority>>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/casos-de-sucesso/citroen-ao-ir-atras-do-publico-alvo-eles-encontraram-compradores</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/insights/covid-2</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/insights/trends</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/insights/covid</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/assets/pdf/mercado-livre-mediakit-PT.pdf</loc>
  <changefreq>monthly</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/casos-de-sucesso/samsung-galaxy-um-lancamento-sob-medida-para-o-usuario</loc>
  <changefreq>monthly</changefreq>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/casos-de-sucesso/ford-casos-de-sucesso</loc>
  <changefreq>monthly</changefreq>
  <priority>0.64</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/assets/reports/covid-2-pt.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/assets/reports/mobile-pt.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/assets/reports/desktop-pt.pdf</loc>
 <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/assets/reports/mobile-en.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/assets/reports/desktop-en.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
<url>
  <loc>https://publicidade-mercadolivre.com/assets/reports/covid-pt.pdf</loc>
  <changefreq>never</changefreq>
  <priority>0.80</priority>
</url>
</urlset>
@endif
